name: bondia-ci-build
on:
  pull_request:
    branches:
    - master
    - develop
  push:
    branches:
    - master
    - develop

jobs:

  lint-code:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install black
      run: pip install black

    - name: Check code with black
      run: |
        black --check .
        black --check scripts/bondia-server

  run-tests:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install apt dependencies
      run: |
        sudo apt update
        sudo apt-get install -y libhdf5-serial-dev libopenmpi-dev libcfitsio-dev

    - name: Clone chimedb_config from private repo
      uses: actions/checkout@v2
      with:
        repository: chime-experiment/chimedb_config
        token: ${{ secrets.ACCESS_TOKEN }}
        path: "chimedb_config"

    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install wheel and future
      run: |
        pip install wheel future

    - name: Install python packages from private repos
      run: |
        pip install --use-deprecated=legacy-resolver ./chimedb_config

    - name: Remove cloned repositories
      run: |
        rm -rf chimedb_config

    - name: Install bondia dependencies
      run: |
        pip install --use-deprecated=legacy-resolver -r requirements.txt
        pip install pytest

    - name: Install bondia
      run: |
        pip install --use-deprecated=legacy-resolver .

    - name: Run tests
      run: pytest .
