name: bondia-ci-build
on:
  pull_request:
    branches:
    - master
    - develop
  push:
    branches:
    - master
    - develop

jobs:

  lint-code:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install black
      run: pip install black

    - name: Check code with black
      run: |
        black --check .
        black --check scripts/bondia-server

  run-tests:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install apt dependencies
      run: |
        sudo apt-get install -y libhdf5-serial-dev libopenmpi-dev libcfitsio-dev

    # Todo: This is a public repo, but chimedb_config uses ssh for this dependency.
    - name: Clone chimedb
      uses: actions/checkout@v2
      with:
        repository: chime-experiment/chimedb
        token: ${{ secrets.ACCESS_TOKEN }}
        path: "chimedb"

    # Todo: This is a public repo, but ch_util uses ssh for this dependency.
    - name: Clone chimedb_di
      uses: actions/checkout@v2
      with:
        repository: chime-experiment/chimedb_di
        token: ${{ secrets.ACCESS_TOKEN }}
        path: "chimedb_di"

    # Todo: This is a public repo, but ch_util uses ssh for this dependency.
    - name: Clone chimedb_dataflag
      uses: actions/checkout@v2
      with:
        repository: chime-experiment/chimedb_dataflag
        token: ${{ secrets.ACCESS_TOKEN }}
        path: "chimedb_dataflag"

    - name: Clone chimedb_config from private repo
      uses: actions/checkout@v2
      with:
        repository: chime-experiment/chimedb_config
        token: ${{ secrets.ACCESS_TOKEN }}
        path: "chimedb_config"

    - name: Clone ch_util from private repo
      uses: actions/checkout@v2
      with:
        repository: chime-experiment/ch_util
        token: ${{ secrets.ACCESS_TOKEN }}
        path: "ch_util"

    - name: Clone ch_pipeline from private repo
      uses: actions/checkout@v2
      with:
        repository: chime-experiment/ch_pipeline
        token: ${{ secrets.ACCESS_TOKEN }}
        path: "ch_pipeline"

    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install wheel and future
      run: |
        pip install wheel future

    - name: Install python packages from private repos
      run: |
        pip install --use-deprecated=legacy-resolver ./ch_util ./chimedb ./chimedb_di ./chimedb_dataflag ./chimedb_config ./ch_pipeline

    - name: Remove cloned repositories
      run: |
        rm -rf chimedb
        rm -rf chimedb_di
        rm -rf chimedb_dataflag
        rm -rf chimedb_config
        rm -rf ch_util

    - name: Install bondia dependencies
      run: |
        pip install --use-deprecated=legacy-resolver -r requirements.txt
        pip install pytest

    - name: Install bondia
      run: |
        pip install --use-deprecated=legacy-resolver .

    - name: Run tests
      run: pytest .
